Mikrotik Identity: Device.DeviceInfo.X_MIKROTIK_SystemIdentity
Product class: InternetGatewayDevice.DeviceInfo.ProductClass
Software version: Device.DeviceInfo.SoftwareVersion
MAC: Device.Ethernet.Interface.1.MACAddress
IP: Device.IP.Interface.1.IPv4Address.1.IPAddress
WLAN SSID: InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID
